apiVersion: v2
name: pogues
description: A Helm chart for Pogues, Pogues-BO and bdd

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 11.6.15
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.1.0
appVersion: "4.0.7"
