{{- if and .Values.api.enabled .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coleman-management.api.serviceAccountName" . }}
  labels:
    {{- include "coleman-management.api.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
