{{- if and .Values.ui.enabled .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "publicEnemy.ui.serviceAccountName" . }}
  labels:
    {{- include "publicEnemy.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
