apiVersion: v2
name: queen
description: A Helm chart for Queen API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.4.0
appVersion: "1.16.0"
