apiVersion: v2
name: queen
description: A Helm chart for Queen API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 13.2.15
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.5.0
appVersion: "4.0.0"
