pogues:
  ui:
    image:
      repository: inseefr/pogues
      pullPolicy: IfNotPresent
      tag: 1.4.1

    ingress:
      hosts:
        - host: pogues-ui.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - pogues-ui.domain.com

    env:
      API_URL: "https://pogues-api.domain.com/api"

  api:
    image:
      repository: inseefr/pogues-back-office
      pullPolicy: IfNotPresent
      tag: 4.0.5

    ingress:
      hosts:
        - host: pogues-api.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - pogues-api.domain.com

    environment:
      ssl: false
      log:
        configuration: classpath:log4j2.xml
      api:
        host: pogues-api.domain.com
        name: ""
        scheme: https
      persistence:
        database:
          host: pogues-db
          port: 5432
          driver: org.postgresql.Driver
          table: Pogues
      authentification: NONE
      role:
        admin: Administrateur_Pogues
        user: Utilisateurs_Pogues
      remote:
        metadata:
          url: https://ddi-access-services.domain.com/api
        stromae:
          host: ""
          vis:
            path: ""
          orbeon:
            host: ""

        queen:
          host: https://queen-ui.domain.com
          vis:
            path: queen/visualize?questionnaire=
        stromaev2:
          vis:
            url: https://stromae-v2.domain.com/visualize?questionnaire=
        eno:
          host: eno-example.local
          scheme: https

  postgresql:
    fullnameOverride: pogues-db
    auth:
      username: Pogues
      password: Pogues
      postgresPassword: postgresPassword
      database: Pogues

eno-ws:
  enoxml:
    image:
      repository: inseefr/eno-ws
      pullPolicy: IfNotPresent
      tag: 1.6.1
    ingress:
      hosts:
        - host: eno-xml.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - eno-xml.domain.com
  enojava:
    enabled: true
    image:
      repository: inseefr/eno-ws
      pullPolicy: IfNotPresent
      tag: ""
    env:
      ENO_LEGACY_WS_URL: https://eno-xml.domain.com
    ingress:
      hosts:
        - host: eno-java.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific

ddi-access-services:
  image:
    repository: inseefr/ddi-access-services
    pullPolicy: IfNotPresent
    tag: 1.0.6

  ingress:
    hosts:
      - host: ddi-access-services.domain.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - ddi-access-services.domain.com

  properties: |-
    # SSL
    fr.insee.rmes.force.ssl=false
    # Log4J configuration File
    fr.insee.rmespogbo.log.configuration=log4j2.xml
    # Swagger host
    fr.insee.rmes.api.host = ddi-access-services.domain.com
    fr.insee.rmes.api.name= /api
    fr.insee.rmes.api.scheme= https
    # Metadata service

    fr.insee.rmes.search.DDIItemRepository.impl = DDIItemRepositoryDBImpl
    fr.insee.rmes.search.db.host = pogues-db
    fr.insee.rmes.search.db.port = 5432
    fr.insee.rmes.search.db.schema = Pogues
    fr.insee.rmes.search.db.user = Pogues
    fr.insee.rmes.search.db.password = Pogues
    fr.insee.rmes.search.db.driver = org.postgresql.Driver
    fr.insee.rmes.search.db.table = ddi_item

queen:
  ui:
    enabled: true
    nameOverride: queen-ui
    replicaCount: 1
    image:
      repository: inseefr/queen
      tag: 0.10.11
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: queen-ui.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - queen-ui.domain.com
    env:
      QUEEN_URL: https://queen-ui.domain.com
      authenticationType: NONE

queen-v2:
  ui:
    enabled: true
    nameOverride: queen-v2-ui
    replicaCount: 1
    image:
      repository: inseefr/queen
      tag: 1.0.1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: queen-v2-ui.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - queen-ui.domain.com
    env:
      QUEEN_URL: https://queen-v2-ui.domain.com
      authenticationType: NONE

stromae-v2:
  ui:
    enabled: true
    nameOverride: stromae-ui
    replicaCount: 1
    image:
      repository: inseefr/stromae
      tag: 2.2.14
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: stromae-v2.domain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - stromae-v2.domain.com
    env:
      AUTHENTICATION_TYPE: NONE
