{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "publicEnemy.api.fullname" . }}
  labels: 
    {{- include "publicEnemy.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "publicEnemy.api.selectorLabels" . | nindent 4 }}
{{- end }}
