apiVersion: v2
name: app
description: A Helm chart for Kubernetes
version: 0.1.1

dependencies:
  - name: postgresql
    version: 10.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-bitnami.enabled
    alias: postgresql-bitnami
#  - name: postgresql-crunchy-instance
#    version: 0.0.1
#    repository: https://inseefr.github.io/Helm-Charts
#    condition: postgresql-crunchy-operator.enabled

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
