{{- if .Values.enoxml.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eno-ws.enoxml.fullname" . }}
  labels:
    {{- include "eno-ws.enoxml.labels" . | nindent 4 }}
spec:
  type: {{ .Values.enoxml.service.type }}
  ports:
    - port: {{ .Values.enoxml.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "eno-ws.enoxml.selectorLabels" . | nindent 4 }}
{{- end -}}